// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Efficient softmax approximation as described in
            /// Efficient softmax approximation for GPUs by Edouard Grave, Armand Joulin,
            /// Moustapha Cissé, David Grangier, and Hervé Jégou.
            /// </summary>
            public partial class AdaptiveLogSoftmaxWithLoss : PythonObject
            {
                // auto-generated class
                
                public AdaptiveLogSoftmaxWithLoss(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
