// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Applies Instance Normalization over a 3D input (a mini-batch of 1D
            /// inputs with optional additional channel dimension) as described in the paper
            /// Instance Normalization: The Missing Ingredient for Fast Stylization .
            /// </summary>
            public partial class InstanceNorm1d : PythonObject
            {
                // auto-generated class
                
                public InstanceNorm1d(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
