// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Applies a 3D adaptive max pooling over an input signal composed of several input planes.
            /// </summary>
            public partial class AdaptiveMaxPool3d : PythonObject
            {
                // auto-generated class
                
                public AdaptiveMaxPool3d(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
