// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Creates a criterion that optimizes a two-class classification
            /// logistic loss between input tensor \(x\) and target tensor \(y\)
            /// (containing 1 or -1).
            /// </summary>
            public partial class SoftMarginLoss : PythonObject
            {
                // auto-generated class
                
                public SoftMarginLoss(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
