// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Applies the \(\log(\text{Softmax}(x))\) function to an n-dimensional
            /// input Tensor. The LogSoftmax formulation can be simplified as:
            /// </summary>
            public partial class LogSoftmax : PythonObject
            {
                // auto-generated class
                
                public LogSoftmax(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
