// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Applies a 3D transposed convolution operator over an input image composed of several input
            /// planes.
            /// The transposed convolution operator multiplies each input value element-wise by a learnable kernel,
            /// and sums over the outputs from all input feature planes.
            /// </summary>
            public partial class ConvTranspose3d : PythonObject
            {
                // auto-generated class
                
                public ConvTranspose3d(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
