// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Creates a criterion that optimizes a multi-class multi-classification
            /// hinge loss (margin-based loss) between input \(x\) (a 2D mini-batch Tensor)
            /// and output \(y\) (which is a 2D Tensor of target class indices).
            /// For each sample in the mini-batch:
            /// </summary>
            public partial class MultiLabelMarginLoss : PythonObject
            {
                // auto-generated class
                
                public MultiLabelMarginLoss(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
