// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Creates a criterion that measures the mean absolute error (MAE) between each element in
            /// the input \(x\) and target \(y\).
            /// </summary>
            public partial class L1Loss : PythonObject
            {
                // auto-generated class
                
                public L1Loss(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
