// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Creates a criterion that optimizes a multi-class classification hinge
            /// loss (margin-based loss) between input \(x\) (a 2D mini-batch Tensor) and
            /// output \(y\) (which is a 1D tensor of target class indices,
            /// \(0 \leq y \leq \text{x.size}(1)-1\)):
            /// </summary>
            public partial class MultiMarginLoss : PythonObject
            {
                // auto-generated class
                
                public MultiMarginLoss(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
