// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// This loss combines a Sigmoid layer and the BCELoss in one single
            /// class. This version is more numerically stable than using a plain Sigmoid
            /// followed by a BCELoss as, by combining the operations into one layer,
            /// we take advantage of the log-sum-exp trick for numerical stability.
            /// </summary>
            public partial class BCEWithLogitsLoss : PythonObject
            {
                // auto-generated class
                
                public BCEWithLogitsLoss(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
