// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Computes the batchwise pairwise distance between vectors \(v_1\), \(v_2\) using the p-norm:
            /// </summary>
            public partial class PairwiseDistance : PythonObject
            {
                // auto-generated class
                
                public PairwiseDistance(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
