// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Creates a criterion that measures the loss given
            /// inputs \(x1\), \(x2\), two 1D mini-batch Tensors,
            /// and a label 1D mini-batch tensor \(y\) (containing 1 or -1).
            /// </summary>
            public partial class MarginRankingLoss : PythonObject
            {
                // auto-generated class
                
                public MarginRankingLoss(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
