// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Rearranges elements in a tensor of shape \((*, C \times r^2, H, W)\)
            /// to a tensor of shape \((*, C, H \times r, W \times r)\).
            /// </summary>
            public partial class PixelShuffle : PythonObject
            {
                // auto-generated class
                
                public PixelShuffle(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
