// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Creates a criterion that measures the triplet loss given an input
            /// tensors \(x1\), \(x2\), \(x3\) and a margin with a value greater than \(0\).
            /// This is used for measuring a relative similarity between samples. A triplet
            /// is composed by a, p and n (i.e., anchor, positive examples and negative
            /// examples respectively). The shapes of all input tensors should be
            /// \((N, D)\).
            /// </summary>
            public partial class TripletMarginLoss : PythonObject
            {
                // auto-generated class
                
                public TripletMarginLoss(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
