// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Applies Batch Normalization over a N-Dimensional input (a mini-batch of [N-2]D inputs
            /// with additional channel dimension) as described in the paper
            /// Batch Normalization: Accelerating Deep Network Training by Reducing Internal Covariate Shift .
            /// </summary>
            public partial class SyncBatchNorm : PythonObject
            {
                // auto-generated class
                
                public SyncBatchNorm(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
