// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Applies the Softmax function to an n-dimensional input Tensor
            /// rescaling them so that the elements of the n-dimensional output Tensor
            /// lie in the range [0,1] and sum to 1.
            /// </summary>
            public partial class Softmax : PythonObject
            {
                // auto-generated class
                
                public Softmax(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
