// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Applies a multi-layer Elman RNN with \(tanh\) or \(ReLU\) non-linearity to an
            /// input sequence.
            /// </summary>
            public partial class RNN : PythonObject
            {
                // auto-generated class
                
                public RNN(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
