// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Implements data parallelism at the module level.
            /// </summary>
            public partial class DataParallel : PythonObject
            {
                // auto-generated class
                
                public DataParallel(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
