// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Allows the model to jointly attend to information
            /// from different representation subspaces.
            /// See reference: Attention Is All You Need
            /// </summary>
            public partial class MultiheadAttention : PythonObject
            {
                // auto-generated class
                
                public MultiheadAttention(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
