// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Applies a bilinear transformation to the incoming data:
            /// \(y = x_1 A x_2 + b\)
            /// </summary>
            public partial class Bilinear : PythonObject
            {
                // auto-generated class
                
                public Bilinear(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
