// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Measures the loss given an input tensor \(x\) and a labels tensor \(y\)
            /// (containing 1 or -1).
            /// This is usually used for measuring whether two inputs are similar or
            /// dissimilar, e.g. using the L1 pairwise distance as \(x\), and is typically
            /// used for learning nonlinear embeddings or semi-supervised learning.
            /// </summary>
            public partial class HingeEmbeddingLoss : PythonObject
            {
                // auto-generated class
                
                public HingeEmbeddingLoss(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
