// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Creates a criterion that optimizes a multi-label one-versus-all
            /// loss based on max-entropy, between input \(x\) and target \(y\) of size
            /// \((N, C)\).
            /// For each sample in the minibatch:
            /// </summary>
            public partial class MultiLabelSoftMarginLoss : PythonObject
            {
                // auto-generated class
                
                public MultiLabelSoftMarginLoss(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
