// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Applies Group Normalization over a mini-batch of inputs as described in
            /// the paper Group Normalization .
            /// </summary>
            public partial class GroupNorm : PythonObject
            {
                // auto-generated class
                
                public GroupNorm(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
