// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// A sequential container.
            /// Modules will be added to it in the order they are passed in the constructor.
            /// Alternatively, an ordered dict of modules can also be passed in.
            /// </summary>
            public partial class Sequential : PythonObject
            {
                // auto-generated class
                
                public Sequential(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
