// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Holds parameters in a list.
            /// 
            /// ParameterList can be indexed like a regular Python
            /// list, but parameters it contains are properly registered, and will be
            /// visible by all Module methods.
            /// </summary>
            public class ParameterList : Module
            {
                // auto-generated class
                
                public ParameterList(PyObject pyobj) : base(pyobj) { }
                
                public ParameterList(params Parameter[] parameters)
                {
                    //auto-generated code, do not change
                    var nn = self.GetAttr("nn");
                    var __self__=nn;
                    var pyargs=ToTuple(parameters);
                    dynamic py = __self__.InvokeMethod("ParameterList", pyargs);
                    self=py as PyObject;
                }
                
                /// <summary>
                /// Appends a given parameter at the end of the list.
                /// </summary>
                public void append(nn.Parameter parameter)
                {
                    var pyargs=ToTuple(new object[]
                    {
                        parameter,
                    });
                    var kwargs=new PyDict();
                    self.InvokeMethod("append", pyargs, kwargs);
                }
                
                /// <summary>
                /// Appends parameters from a Python iterable to the end of the list.
                /// </summary>
                public void extend(params Parameter[] parameters)
                {
                    var pyargs=ToTuple(parameters);
                    var kwargs=new PyDict();
                    self.InvokeMethod("extend", pyargs, kwargs);
                }
                
            }
        }
    }
    
}
