// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            public static partial class parallel {
                /// <summary>
                /// Implements distributed data parallelism that is based on
                /// torch.distributed package at the module level.
                /// </summary>
                public partial class DistributedDataParallel : PythonObject
                {
                    // auto-generated class
                    
                    public DistributedDataParallel(PyObject pyobj) : base(pyobj) { }
                    
                }
            }
        }
    }
    
}
