// Code generated by CodeMinion: https://github.com/SciSharp/CodeMinion

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Python.Runtime;
using Numpy;
using Numpy.Models;

namespace Torch
{
    public static partial class torch {
        public static partial class nn {
            /// <summary>
            /// Creates a criterion that measures the Binary Cross Entropy
            /// between the target and the output:
            /// </summary>
            public partial class BCELoss : PythonObject
            {
                // auto-generated class
                
                public BCELoss(PyObject pyobj) : base(pyobj) { }
                
            }
        }
    }
    
}
