//Generated by Regex Templating Engine at 15/07/2019 14:02:17 UTC
//template source: C:\Users\Eli-PC\Desktop\CodeMinion\test\Regen.Core.UnitTest\Package\tempfilename.template.cs

namespace RegenApp {
    public class templatefileFLOAT {

        public float Add(float left, float right) {
            return left + right;
        }

    }
}

